name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pyenv
      run: |
        curl https://pyenv.run | bash
        echo 'PYENV_ROOT="$HOME/.pyenv"' >> $GITHUB_ENV
        echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> $GITHUB_ENV
        echo 'eval "$(pyenv init -)"'  >> $GITHUB_ENV
        echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
        echo "WOW"
        source $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }} with pyenv
      env:
        PYENV_ROOT: ${{ env.PYENV_ROOT }}
        PATH: ${{ env.PATH }}
      run: |
        pyenv install ${{ matrix.python-version }} -s
        pyenv virtualenv ${{ matrix.python-version }} venv
        echo "venv" > .python-version
        pyenv activate venv
        echo "PYENV_VERSION=venv" >> $GITHUB_ENV

    - name: Install dependencies
      env:
        PYENV_ROOT: ${{ env.PYENV_ROOT }}
        PATH: ${{ env.PATH }}
        PYENV_VERSION: venv
      run: |
        python -m pip install --upgrade pip
        pip install pytest responses
        pip install .

    - name: Run tests
      env:
        PYENV_ROOT: ${{ env.PYENV_ROOT }}
        PATH: ${{ env.PATH }}
        PYENV_VERSION: venv
      run: |
        JITO_TESTNET_URL=https://dallas.testnet.block-engine.jito.wtf/api/v1 pytest ./tests/test_jito_json_rpc_sdk.py
